import { Memory } from '../types/memory';

export const INITIAL_DEMO_MEMORIES: Memory[] = [
  {
    id: '11111111-1111-1111-1111-111111111111',
    image_url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
    title: 'Blue Handbag',
    summary: 'A blue handbag you saw at Lifestyle Store on 12 Aug 2026.',
    memory_type: 'object',
    source: 'camera',
    category: 'Objects',
    object_name: 'Blue Handbag',
    place_name: 'Lifestyle Store',
    brand: 'Lavie',
    model: 'Classic Tote',
    price: '1499',
    currency: 'INR',
    visible_text: ['Lavie', 'Special Offer'],
    colors: ['navy blue', 'gold hardware'],
    description: 'A blue handbag you saw at Lifestyle Store on 12 Aug 2026 with matching gold hardware charm.',
    important_details: ['Dual handles', 'Zippered closure', 'Matching gold charm'],
    location: 'Lifestyle Store',
    latitude: 13.0583,
    longitude: 80.2642,
    captured_at: '2026-08-12T15:30:00.000Z',
    confidence: 0.94,
    is_demo: true,
  },
  {
    id: '66666666-6666-6666-6666-666666666666',
    image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
    title: 'White Sneakers',
    summary: 'White sneakers you saw at Sports Store on 10 Aug 2026.',
    memory_type: 'product',
    source: 'camera',
    category: 'Objects',
    object_name: 'White Sneakers',
    place_name: 'Sports Store',
    brand: 'Nike',
    model: 'Air Cushion',
    price: '3499',
    currency: 'INR',
    visible_text: ['Nike', 'Air', 'Size 9'],
    colors: ['clean white', 'light grey accents'],
    description: 'White sports sneakers with cushioned sole displayed on the middle rack at Sports Store.',
    important_details: ['Breathable mesh upper', 'Foam midsole', 'Sale offer valid this week'],
    location: 'Sports Store',
    latitude: 12.9915,
    longitude: 80.2180,
    captured_at: '2026-08-10T16:45:00.000Z',
    confidence: 0.95,
    is_demo: true,
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    image_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
    title: 'Café',
    summary: 'Cozy café interior and artisan coffee cup on Beach Road, Chennai.',
    memory_type: 'place',
    source: 'camera',
    category: 'Places',
    object_name: null,
    place_name: 'Beachside Roasters',
    brand: null,
    model: null,
    price: null,
    currency: null,
    visible_text: ['Specialty Coffee', 'Roasted in Chennai'],
    colors: ['amber brown', 'warm teak wood', 'terracotta'],
    description: 'Handcrafted cold brew coffee served on an outdoor wooden patio overlooking the ocean shore in Chennai.',
    important_details: ['Seaside patio seating', 'Roasted in-house weekly', 'Quiet study spot'],
    location: 'Chennai',
    latitude: 12.9815,
    longitude: 80.2680,
    captured_at: '2026-08-08T11:20:00.000Z',
    confidence: 0.95,
    is_demo: true,
  },
  {
    id: '33333333-3333-3333-3333-333333333333',
    image_url: 'https://images.unsplash.com/photo-1544717297-fa95b6ee9643?auto=format&fit=crop&w=800&q=80',
    title: 'Passport',
    summary: 'International passport and travel documents kept safely in the desk drawer at Home.',
    memory_type: 'document',
    source: 'camera',
    category: 'Documents',
    object_name: 'Passport',
    place_name: 'Home Desk',
    brand: null,
    model: null,
    price: null,
    currency: null,
    visible_text: ['Passport', 'Republic of India', 'Official Document'],
    colors: ['deep navy', 'gold emblem'],
    description: 'International travel passport document kept inside study drawer for safe keeping.',
    important_details: ['Stored in top desk drawer', 'Valid through 2032'],
    location: 'Home',
    latitude: 13.0827,
    longitude: 80.2707,
    captured_at: '2026-08-05T10:00:00.000Z',
    confidence: 0.98,
    is_demo: true,
  },
  {
    id: '44444444-4444-4444-4444-444444444444',
    image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    title: 'Atomic Habits',
    summary: 'Hardcover personal development book seen on the study desk.',
    memory_type: 'book',
    source: 'upload',
    category: 'Objects',
    object_name: 'Atomic Habits Book',
    place_name: null,
    brand: 'James Clear',
    model: null,
    price: null,
    currency: null,
    visible_text: ['Atomic Habits', 'Tiny Changes, Remarkable Results', 'James Clear'],
    colors: ['off-white', 'lemon yellow dot', 'black typography'],
    description: 'Hardcover edition of Atomic Habits book resting on study table beside reading lamp.',
    important_details: ['Bookmark at chapter 4', 'Key insight: 1% better every day'],
    location: 'Home Desk',
    latitude: 13.0827,
    longitude: 80.2707,
    captured_at: '2026-08-02T21:40:00.000Z',
    confidence: 0.96,
    is_demo: true,
  },
  {
    id: '88888888-8888-8888-8888-888888888888',
    image_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
    title: 'AR Rahman Concert Pass',
    summary: 'VIP zone entry ticket pass for the live arena performance.',
    memory_type: 'ticket',
    source: 'camera',
    category: 'Experiences',
    object_name: 'Concert Entry Pass',
    place_name: 'YMCA Grounds',
    brand: null,
    model: null,
    price: null,
    currency: null,
    visible_text: ['AR Rahman Live in Concert', 'Gate 3', 'VIP Lounge', 'Admit One'],
    colors: ['deep violet', 'neon cyan', 'silver holographic'],
    description: 'VIP zone arena pass for live concert with holographic security watermark.',
    important_details: ['Admit One', 'Gate 3 access', 'QR code verified'],
    location: 'YMCA Grounds, Chennai',
    latitude: 13.0285,
    longitude: 80.2412,
    captured_at: '2026-07-28T19:00:00.000Z',
    confidence: 0.97,
    is_demo: true,
  },
];

export const DEMO_QUESTIONS = [
  'Where did I see that café?',
  'Have I seen these shoes before?',
  'When did I see this?',
  'Where was this photo taken?',
];
