import { Memory } from '../types/memory';

export const INITIAL_DEMO_MEMORIES: Memory[] = [
  {
    id: '11111111-1111-1111-1111-111111111111',
    image_url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
    title: 'Blue Handbag',
    summary: 'Navy blue leatherette shoulder tote bag seen on a display shelf at Lifestyle Store.',
    memory_type: 'object',
    source: 'camera',
    category: 'Objects',
    object_name: 'Blue Handbag',
    place_name: 'Lifestyle Store',
    brand: 'Lavie',
    model: 'Classic Tote',
    price: '1499',
    currency: 'INR',
    visible_text: ['Lavie', 'Special Offer'],
    colors: ['navy blue', 'gold hardware'],
    description: 'Navy blue leatherette shoulder tote bag on display shelf with matching gold hardware charm.',
    important_details: ['Dual handles', 'Zippered closure', 'Matching gold charm'],
    location: 'Lifestyle Store, Express Avenue, Chennai',
    latitude: 13.0583,
    longitude: 80.2642,
    captured_at: '2026-09-02T15:30:00.000Z',
    confidence: 0.94,
    is_demo: true,
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    image_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
    title: 'Artisan Coffee Shop',
    summary: 'Cold brew coffee and seaside café interior with wooden deck on Beach Road.',
    memory_type: 'place',
    source: 'camera',
    category: 'Places',
    object_name: null,
    place_name: 'Beachside Roasters',
    brand: null,
    model: null,
    price: null,
    currency: null,
    visible_text: ['Beachside Roasters', 'Specialty Coffee', 'Roasted in Chennai'],
    colors: ['amber brown', 'warm teak wood', 'terracotta'],
    description: 'Handcrafted cold brew coffee served on an outdoor wooden patio overlooking the ocean shore.',
    important_details: ['Seaside patio seating', 'Roasted in-house weekly', 'Quiet study spot'],
    location: 'Beachside Roasters, Beach Road, Chennai',
    latitude: 12.9815,
    longitude: 80.2680,
    captured_at: '2026-08-29T11:20:00.000Z',
    confidence: 0.95,
    is_demo: true,
  },
  {
    id: '33333333-3333-3333-3333-333333333333',
    image_url: 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?auto=format&fit=crop&w=800&q=80',
    title: 'College Degree Certificate',
    summary: 'Bachelor of Technology graduation certificate containing degree completion details.',
    memory_type: 'document',
    source: 'camera',
    category: 'Documents',
    object_name: null,
    place_name: 'Anna University Campus',
    brand: null,
    model: null,
    price: null,
    currency: null,
    visible_text: ['Bachelor of Technology', 'First Class with Distinction', 'Anna University', 'Official Seal'],
    colors: ['parchment white', 'navy blue border', 'embossed gold'],
    description: 'Official degree completion certificate document with university seal and registrar signature.',
    important_details: ['Official seal verified', 'First class distinction', 'Kept in blue graduation folio'],
    location: 'Anna University, Guindy, Chennai',
    latitude: 13.0102,
    longitude: 80.2354,
    captured_at: '2026-08-25T10:00:00.000Z',
    confidence: 0.98,
    is_demo: true,
  },
  {
    id: '44444444-4444-4444-4444-444444444444',
    image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    title: 'Atomic Habits',
    summary: 'Hardcover personal development book seen on the study desk.',
    memory_type: 'book',
    source: 'upload',
    category: 'Books',
    object_name: 'Atomic Habits Book',
    place_name: null,
    brand: 'James Clear',
    model: null,
    price: null,
    currency: null,
    visible_text: ['Atomic Habits', 'Tiny Changes, Remarkable Results', 'James Clear', 'An Easy & Proven Way'],
    colors: ['off-white', 'lemon yellow dot', 'black typography'],
    description: 'Hardcover edition of Atomic Habits book resting on study table beside brass reading lamp.',
    important_details: ['Bookmark at chapter 4', 'Key insight: 1% better every day', 'Loaned from library'],
    location: 'Study Desk, Chennai',
    latitude: 13.0827,
    longitude: 80.2707,
    captured_at: '2026-08-22T21:40:00.000Z',
    confidence: 0.96,
    is_demo: true,
  },
  {
    id: '55555555-5555-5555-5555-555555555555',
    image_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    title: 'Kapaleeshwarar Temple',
    summary: 'Historic 7th-century Dravidian temple gopuram captured in Mylapore.',
    memory_type: 'place',
    source: 'google_photos',
    is_imported: true,
    category: 'Places',
    object_name: null,
    place_name: 'Kapaleeshwarar Temple',
    brand: null,
    model: null,
    price: null,
    currency: null,
    visible_text: ['Arulmigu Kapaleeshwarar Temple', 'Mylapore'],
    colors: ['terracotta orange', 'sky blue', 'sunlit gold'],
    description: 'Ornate multi-tiered temple tower featuring detailed sculpted deities and bright traditional colors against evening sky.',
    important_details: ['7-tiered rajagopuram', 'Ancient Chola/Pallava style', 'Water tank adjacent'],
    location: 'Mylapore, Chennai',
    latitude: 13.0334,
    longitude: 80.2697,
    captured_at: '2026-08-18T17:45:00.000Z',
    confidence: 0.95,
    is_demo: true,
  },
  {
    id: '66666666-6666-6666-6666-666666666666',
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    title: 'Running Shoes',
    summary: 'Crimson red lightweight running sneakers displayed on shoe rack.',
    memory_type: 'product',
    source: 'camera',
    category: 'Products',
    object_name: 'Nike Revolution 7',
    place_name: 'Sports Store',
    brand: 'Nike',
    model: 'Revolution 7',
    price: '3499',
    currency: 'INR',
    visible_text: ['Nike', '₹3,499', 'Size UK 9'],
    colors: ['crimson red', 'white sole', 'black swoosh'],
    description: 'Crimson red lightweight running sneakers displayed on store shelf with cushioned heel and discount sticker.',
    important_details: ['Breathable mesh upper', 'Foam midsole', 'Sale offer valid this week'],
    location: 'Sports Store, Phoenix Marketcity, Chennai',
    latitude: 12.9915,
    longitude: 80.2180,
    captured_at: '2026-08-17T16:45:00.000Z',
    confidence: 0.95,
    is_demo: true,
  },
  {
    id: '77777777-7777-7777-7777-777777777777',
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    title: 'Handcrafted Brass Filter Coffee Pot',
    summary: 'Traditional South Indian brass coffee dabarah and decoction set received as a birthday gift.',
    memory_type: 'object',
    source: 'upload',
    category: 'Objects',
    object_name: 'Traditional Brass Coffee Pot',
    place_name: 'Family Home',
    brand: 'Kumbakonam Heritage Brass',
    model: null,
    price: null,
    currency: null,
    visible_text: ['Pure Brass', 'Handmade Kumbakonam'],
    colors: ['gleaming brass gold', 'warm bronze'],
    description: 'Traditional solid brass South Indian filter coffee maker set resting on dining table.',
    important_details: ['Gift from family', 'Pure virgin brass', 'Traditional 2-cup capacity'],
    location: 'Chennai',
    latitude: 13.0827,
    longitude: 80.2707,
    captured_at: '2026-08-15T09:30:00.000Z',
    confidence: 0.93,
    is_demo: true,
  },
  {
    id: '88888888-8888-8888-8888-888888888888',
    image_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
    title: 'AR Rahman Live Concert Pass',
    summary: 'VIP zone entry ticket pass for the live arena performance.',
    memory_type: 'ticket',
    source: 'camera',
    category: 'Experiences',
    object_name: 'Concert Entry Pass',
    place_name: 'YMCA Grounds',
    brand: null,
    model: null,
    price: null,
    currency: null,
    visible_text: ['AR Rahman Live in Concert', 'Gate 3', 'VIP Lounge', 'Admit One'],
    colors: ['deep violet', 'neon cyan', 'silver holographic'],
    description: 'VIP zone arena pass for live concert with holographic security watermark.',
    important_details: ['Admit One', 'Gate 3 access', 'QR code verified'],
    location: 'YMCA Grounds, Nandanam, Chennai',
    latitude: 13.0285,
    longitude: 80.2412,
    captured_at: '2026-08-10T19:00:00.000Z',
    confidence: 0.97,
    is_demo: true,
  },
];

export const DEMO_QUESTIONS = [
  'Where did I see that blue handbag?',
  'What did I see at the coffee shop?',
  'Have I seen this book before?',
  'What documents have I captured?',
  'Show me places I visited in Chennai',
  'What was that concert ticket I saved?',
];
